# Generated by Django 5.0 on 2024-05-28 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
