# Generated by Django 5.0 on 2024-05-21 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.ForeignKey(default='...', on_delete=django.db.models.deletion.CASCADE, to='college_admin.semester'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(default='...', on_delete=django.db.models.deletion.CASCADE, to='college_admin.course'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='course',
            field=models.ForeignKey(default='...', on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='college_admin.course'),
        ),
    ]
