# Generated by Django 5.0 on 2024-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0003_alter_course_semester_alter_enrollment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='college_admin.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='students', to='college_admin.specialization'),
        ),
    ]
