# Generated by Django 5.0 on 2024-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0005_enrollment_specializations_alter_student_courses_and_more'),
        ('manage_students', '0002_delete_formdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_info',
            field=models.ManyToManyField(blank=True, to='manage_students.personalinfo'),
        ),
    ]
