# Generated by Django 5.0 on 2024-05-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0006_student_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='courses',
            field=models.ManyToManyField(blank=True, to='college_admin.course'),
        ),
        migrations.AddField(
            model_name='message',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='college_admin.specialization'),
        ),
    ]
