# Generated by Django 5.0 on 2024-06-04 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_admin', '0008_remove_course_semester_student_enrollment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField()),
                ('employer_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college_admin.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college_admin.student')),
            ],
        ),
    ]
