# Generated by Django 5.0 on 2024-04-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='main_category',
            field=models.CharField(choices=[('EXT', 'Exterior'), ('INT', 'Interior'), ('COM', 'Combos')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[], default='', max_length=20),
        ),
    ]
