# Generated by Django 5.0 on 2024-04-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_category_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('EXT', [('SH', 'Shampoo'), ('FC', 'Foam Cannon'), ('MS', 'Mitts and Sponges'), ('BR', 'Brushes'), ('TW', 'Towels'), ('BK', 'Buckets'), ('WT', 'Wheel and Tire Cleaners'), ('WS', 'Wax and Sealants'), ('CB', 'Clay Bars'), ('GC', 'Glass Cleaners'), ('OT', 'Other Exterior Accessories')]), ('INT', [('SH', 'Shampoo'), ('IC', 'Interior Cleaners'), ('WT', 'Wax and Treatments'), ('VC', 'Vacuum Cleaners'), ('BS', 'Brushes and Scrubbers'), ('SR', 'Stain Removers'), ('AP', 'Air Purifiers'), ('ST', 'Steering Wheel Covers'), ('OT', 'Other Interior Accessories')]), ('COM', [('KIT', 'Complete Car Care Kits'), ('PKG', 'Detailing Packages'), ('CMBO', 'Exterior and Interior Combos'), ('OT', 'Other Combo Kits')])], default='', max_length=20),
        ),
    ]
