# Generated by Django 5.0 on 2024-05-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('shop', '0004_remove_product_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(limit_choices_to={'category': models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.category')}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.subcategory'),
        ),
    ]
